#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/lily/data'
LOG: '/srv/data/lily/log'
DATASET: 'pnl_change_5'
# DATASET: 'nonlinear_gau_ns'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'gaussian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 8
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/lily/ckpts/spline_nonlinear_gau_ins.pth'
  
VAE:
    GPU: [1]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 256
    EPOCHS: 50
    N_VAL_SAMPLES: 1024
    LAG: 2
    LENGTH: 1
    NCLASS: 5
    TRANS_PRIOR: 'NP'
    LR: 2.0e-3
    BETA: 2.0e-3
    GAMMA: 2.0e-2
    SIGMA: 1.0e-6
    L1: 0.0
    INPUT_DIM: 8
    LATENT_DIM: 8
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman'