#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/lily/data'
LOG: '/srv/data/lily/log'
DATASET: 'pnl_modular_5'

SPLINE:
    OBS_DIM: 1
    OBS_EMBED_DIM: 2
    BOUND: 5
    BINS: 8
    ORDER: 'linear'

VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 64
    VAL_BS: 256
    EPOCHS: 100
    N_VAL_SAMPLES: 1024
    NCLASS: 5
    LAG: 2
    LENGTH: 1
    INPUT_DIM: 9
    DYN_DIM: 8
    DYN_EMBED_DIM: 2
    INFER_MODE: 'F'
    TRANS_PRIOR: 'NP'
    LR: 5.0e-4
    BETA: 2.0e-3
    GAMMA: 2.0e-2
    SIMGA: 5.0e-4
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman'