#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/lily/data'
LOG: '/srv/data/lily/log'
DATASET: 'pnl_2lag'
  
VAE:
    GPU: [1]
    CPU: 8
    TRAIN_BS: 64
    VAL_BS: 256
    EPOCHS: 50
    N_VAL_SAMPLES: 1024
    LAG: 2
    LENGTH: 1
    TRANS_PRIOR: 'NP'
    LR: 5.0e-4
    BETA: 3.0e-3
    GAMMA: 1.0e-2
    INPUT_DIM: 8
    LATENT_DIM: 8
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman'